#!/bin/sh

# Extract colors from Pywal's JSON file
background=$(jq -r '.special.background' ~/.cache/wal/colors.json)
# foreground=$(jq -r '.special.foreground' ~/.cache/wal/colors.json) 
foreground=$(jq -r '.colors.color5' ~/.cache/wal/colors.json) 
frame_color=$(jq -r '.colors.color1' ~/.cache/wal/colors.json)
highlight=$(jq -r '.colors.color5' ~/.cache/wal/colors.json)

# Print the extracted colors to verify
echo "Background: $background"
echo "Foreground: $foreground"
echo "Frame Color: $frame_color"
echo "Highlight: $highlight"

# Write new Dunst configuration
cat <<EOF > ~/.config/i3/dunst/dunstrc    #Change file path if dunstrc isn't in the deafault path
[global]
    # Display
    monitor = 1
    follow = keyboard
    origin = top-right
	offset = (24, 56)
    width = 501
    height = (0, 300)
    indicate_hidden = yes
    shrink = no
    transparency = 0
    separator_height = 2
    padding = 15
    horizontal_padding = 15
    frame_width = 3
    frame_color = "$frame_color"
	background = "$background"
    separator_color = auto
    sort = yes
    idle_threshold = 120

    # Text
    font = JetBrainsMono Nerd Font 11
    line_height = 2
    markup = full
    format = "<b>%s</b>\n%b"
    alignment = left
    vertical_alignment = center
    show_age_threshold = 30
    word_wrap = yes
    ellipsize = middle
    ignore_newline = yes
    stack_duplicates = true
    hide_duplicate_count = false
    show_indicators = yes

    # Icons
    icon_position = left
    min_icon_size = 16
    max_icon_size = 32
    enable_recursive_icon_lookup = true
    icon_path = /usr/share/icons/Papirus/96x96/devices/:/usr/share/icons/Papirus/48x48/status/:/usr/share/icons/Papirus/96x96/apps/

    # History
    sticky_history = yes
    history_length = 20

    # Advanced
    dmenu= /usr/bin/dmenu -p dunst:
    browser = /usr/bin/firefox -new-tab
    always_run_script = true
    title = Dunst
    class = Dunst
    corner_radius = 0
    force_xinerama = false

    # Progress bar
    progress_bar = true
    progress_bar_height = 10
    progress_bar_frame_width = 1
    progress_bar_min_width = 150
    progress_bar_max_width = 300
    # Misc
    notification_limit = 5
    ignore_dbusclose = false

    # Mouse actions
    mouse_left_click = close_current
    mouse_middle_click = do_action
    mouse_right_click = close_all

    # Keyboard shortcuts
    close = ctrl+space
    close_all = ctrl+shift+space
    history = ctrl+grave
    context = ctrl+shift+period

[experimental]
    per_monitor_dpi = false

[urgency_low]
    background = "$background"
    foreground = "$foreground"
    frame_color = "$frame_color"
    timeout = 10
    highlight = "$highlight"

[urgency_normal]
    background = "$background"
    foreground = "$foreground"
    frame_color = "$frame_color"
    timeout = 10
    highlight = "$highlight"

[urgency_critical]
    background = "$background"
    foreground = "$foreground"
    frame_color = "$frame_color"
    timeout = 30
    highlight = "$highlight"
EOF

# Restart Dunst to apply changes
killall dunst 
dunst -config ~/.config/i3/dunst/dunstrc &
